import pickle

def pick(hypo, filename):
    """
    pickle the hypothesis
    :param hypo: The generated bypothesis
    :param filename: The output file name
    """
    outfile = open("Output/" + filename, 'wb')
    pickle.dump(hypo, outfile)
    outfile.close()
    
def unpick(filename):
    """
    unpickle the hypothesis
    :param filename: The input file of hypothesis
    :return: The hypothesis
    """
    infile = open(filename,'rb')
    return pickle.load(infile, encoding='latin1')